### ISSUE TITLE
How to add child dynamically? 

### ISSUE THREAD

**Issue by opensourcegps** [darioielardi/flutter_speed_dial#6]
I'm trying to change children in current SpeedDial widget. However once I setState to refresh the view, I get the following error:

```
I/flutter ( 4942): _renderSpeedDial
I/flutter ( 4942): [Instance of 'SpeedDialChild', Instance of 'SpeedDialChild']
I/flutter ( 4942): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4942): The following RangeError was thrown building SpeedDial(dirty, state: _SpeedDialState#ac3e1(tickers:
I/flutter ( 4942): tracking 2 tickers)):
I/flutter ( 4942): RangeError (index): Invalid value: Only valid value is 0: 1
I/flutter ( 4942): 
I/flutter ( 4942): When the exception was thrown, this was the stack:
I/flutter ( 4942): #0      List.[] (dart:core/runtime/libgrowable_array.dart:141:60)
I/flutter ( 4942): #1      _SpeedDialState._getChildrenList.<anonymous closure> (package:flutter_speed_dial/src/speed_dial.dart:148:43)
I/flutter ( 4942): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
I/flutter ( 4942): #3      ListIterable.toList (dart:_internal/iterable.dart:219:19)
I/flutter ( 4942): #4      _SpeedDialState._getChildrenList (package:flutter_speed_dial/src/speed_dial.dart:163:10)
I/flutter ( 4942): #5      _SpeedDialState._renderButton (package:flutter_speed_dial/src/speed_dial.dart:195:23)
I/flutter ( 4942): #6      _SpeedDialState.build (package:flutter_speed_dial/src/speed_dial.dart:230:9)
I/flutter ( 4942): #7      StatefulElement.build (package:flutter/src/widgets/framework.dart:3743:27)
I/flutter ( 4942): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
I/flutter ( 4942): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 4942): #10     StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 4942): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 4942): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 4942): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 4942): #14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter ( 4942): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter ( 4942): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:214:5)
I/flutter ( 4942): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 4942): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 4942): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 4942): #20     _invoke (dart:ui/hooks.dart:128:13)
I/flutter ( 4942): #21     _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter ( 4942): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
It looks like speed dial instance remembers old number of children and does not accept new child in the list.

Here is how speed dial is rendered:

```
List <SpeedDialChild> _childrenWidgets = []; 

var _childSingle = SpeedDialChild(
                          child: Icon(fire, color: Colors.white),
                          backgroundColor: _color,
                          onTap: () {
                          },
                          label: _name,
                        );

_childrenWidgets.add(_childSingle);

  return new SpeedDial(
        child: _icon,
        onOpen: () => print('OPENING DIAL'),
        onClose: () => print('DIAL CLOSED'),
        visible: _dialVisible,
        curve: Curves.bounceIn,
        children: _childrenWidgets,

      );

```
Once I add new item into _childrenWidgets list and setState, I get the crash. Is there any way to add children dynamically?

At the moment I'm using really ugly workaround to replace speedDial completely, setState, and then after small delay, put new speedDial back with updated children.

**Comment by Anvin-HSS** [comment]
How to add scrolling in children ?
